server:
  port: 8010

#微服务的名字
spring:
  application:
    name: provider  #服务生产者
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #注册中心访问地址

  instance:
    prefer-ip-address: true  #是否将当前服务的IP注册到EurekaServcer
    lease-renewal-interval-in-seconds: 3 #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 6 #服务刷新时间配置，每隔这个时间会主动心跳一次


